// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3jDPWtZ21tpQGZzwKqPwuOoUKHUvOdfY',
    appId: '1:558194793862:android:3c24e94cb975f6c29e6007',
    messagingSenderId: '558194793862',
    projectId: 'decisive-plasma-415707',
    databaseURL: 'https://decisive-plasma-415707-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'decisive-plasma-415707.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV43xrQIpG19qMTCc1pHy26MHSozyg6NM',
    appId: '1:558194793862:ios:3e4f25ad323d2af49e6007',
    messagingSenderId: '558194793862',
    projectId: 'decisive-plasma-415707',
    databaseURL: 'https://decisive-plasma-415707-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'decisive-plasma-415707.firebasestorage.app',
    iosBundleId: 'com.example.trissea',
  );
}
